[package]
name = "ricochet_robots"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = "0.26.3"
strum_macros = "0.26.4"
fnv = "1.0.7"
bitvec = "1.0.1"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "profile"
path = "src/profile.rs"
